/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-09-24 09:56:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1600941330861L));
    _jspx_dependants.put("jar:file:/C:/workspace/udonmarket/udonmarket/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspace/udonmarket/udonmarket/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspace/udonmarket/udonmarket/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_fmt_005frequestEncoding_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageTitle", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("마이페이지", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("<!-- mypage css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/mypage.css\">\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("a{text-decoration: none; color: black;}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("    <!--================Home Banner Area =================-->\n");
      out.write("    <!-- breadcrumb start-->\n");
      out.write("\t<section class=\"breadcrumb breadcrumb_bg\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row justify-content-center\">\n");
      out.write("                <div class=\"col-lg-8\">\n");
      out.write("                    <div class=\"breadcrumb_iner\">\n");
      out.write("                        <div class=\"breadcrumb_iner_item\">\n");
      out.write("                            <h2>마이페이지</h2>\n");
      out.write("\t\t\t\t\t\t\t<!-- <h3>서울 강남구 논현동</h3> -->\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("    <!-- breadcrumb start-->\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    <div class=\"row py-5 px-4\">\n");
      out.write("\t    <div class=\"col-md-5 mx-auto\">\n");
      out.write("\t        <!-- Profile widget -->\n");
      out.write("\t        <div class=\"bg-white shadow rounded overflow-hidden\">\n");
      out.write("\t            <div class=\"px-4 pt-0 pb-4 cover\">\n");
      out.write("\t                <div class=\"media align-items-end profile-head\">\n");
      out.write("\t                    <div class=\"profile mr-3\"><img src=\"https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80\" alt=\"...\" width=\"130\" class=\"rounded mb-2 img-thumbnail\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/editprofile\" class=\"btn btn-outline-dark btn-sm btn-block\">Edit profile</a></div>\n");
      out.write("\t                    <div class=\"media-body mb-5 text-white\">\n");
      out.write("\t                        <h4 class=\"mt-0 mb-0\" style=\"color:white;\">Mark Williams</h4>\n");
      out.write("\t                        <p class=\"small mb-4\" style=\"color:white;\"> <i class=\"fas fa-map-marker-alt mr-2\"></i>New York</p>\n");
      out.write("\t                    </div>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("\t            <div class=\"bg-light p-4 d-flex justify-content-end text-center\">\n");
      out.write("\t                <ul class=\"list-inline mb-0\">\n");
      out.write("\t                    <li class=\"list-inline-item\">            \n");
      out.write("\t                       <h6 class=\"font-weight-bold mb-0 d-block\">\t                       \t\n");
      out.write("\t                       \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/salesList\">\n");
      out.write("\t                       \t\t<i class=\"fas fa-receipt fa-2x\" ></i> <br /> 판매내역\n");
      out.write("\t                       \t</a>\n");
      out.write("\t                       </h6>\n");
      out.write("\t                    </li>\n");
      out.write("\t                    <li class=\"list-inline-item\">\n");
      out.write("\t                    \t<h6 class=\"font-weight-bold mb-0 d-block\">\t                       \t\n");
      out.write("\t                       \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/buyList\">\n");
      out.write("\t                       \t\t<i class=\"fas fa-shopping-bag fa-2x\" ></i> <br /> 구매내역\n");
      out.write("\t                       \t</a>\n");
      out.write("\t                       </h6>\n");
      out.write("\t                    </li>\n");
      out.write("\t                    <li class=\"list-inline-item\">\n");
      out.write("\t                    \t<h6 class=\"font-weight-bold mb-0 d-block\">\t                       \t\n");
      out.write("\t                       \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/wishList\">\n");
      out.write("\t                       \t\t<i class=\"fas fa-heart fa-2x\" ></i> <br /> 관심목록\n");
      out.write("\t                       \t</a>\n");
      out.write("\t                       </h6>\n");
      out.write("\t                    </li>\n");
      out.write("\t                </ul>\n");
      out.write("\t            </div>\n");
      out.write("\t            <div class=\"px-4 py-3\">\n");
      out.write("\t                <div class=\"p-4 rounded shadow-sm bg-light\">\n");
      out.write("\t\t\t\t        <!-- Vertical Menu-->\n");
      out.write("\t\t\t\t        <nav class=\"nav flex-column bg-white shadow-sm rounded p-3\">\n");
      out.write("\t\t\t\t          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/settingsArea\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t                           <i class=\"fas fa-map-marker-alt\"></i>&nbsp; 내 동네 설정\n");
      out.write("\t                      </a>\n");
      out.write("\t\t\t\t          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/keywordNoti\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t\t                      <i class=\"fas fa-tag\"></i>&nbsp; 키워드 알림\n");
      out.write("\t                      </a>\n");
      out.write("<!-- \t\t\t\t          <a href=\"#\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t\t                      <i class=\"fas fa-th-large\"></i>&nbsp; 모아보기\n");
      out.write("\t                      </a> -->\n");
      out.write("\t\t\t\t          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/myReviewList\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t\t                      <i class=\"far fa-smile\"></i>&nbsp; 받은 거래 후기\n");
      out.write("\t                      </a>\n");
      out.write("\t\t\t\t        </nav>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("\t            <div class=\"px-4 py-3\">\n");
      out.write("\t                <div class=\"p-4 rounded shadow-sm bg-light\">\n");
      out.write("\t\t\t\t        <!-- Vertical Menu-->\n");
      out.write("\t\t\t\t        <nav class=\"nav flex-column bg-white shadow-sm rounded p-3\">\n");
      out.write("\t\t\t\t          <a href=\"#\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t                           <i class=\"far fa-edit\"></i>&nbsp; 동네생활 글\n");
      out.write("\t                      </a>\n");
      out.write("\t\t\t\t          <a href=\"#\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t\t                      <i class=\"far fa-comment-dots\"></i>&nbsp; 동네생활 댓글\n");
      out.write("\t                      </a>\n");
      out.write("\t\t\t\t          <a href=\"#\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t\t                      <i class=\"far fa-star\"></i>&nbsp; 관심 주제 목록\n");
      out.write("\t                      </a>\n");
      out.write("\t\t\t\t        </nav>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("\t            <div class=\"px-4 py-3\">\n");
      out.write("\t                <div class=\"p-4 rounded shadow-sm bg-light\">\n");
      out.write("\t\t\t\t        <!-- Vertical Menu-->\n");
      out.write("\t\t\t\t        <nav class=\"nav flex-column bg-white shadow-sm rounded p-3\">\n");
      out.write("\t\t\t\t          <a href=\"#\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t                           <i class=\"far fa-envelope\"></i>&nbsp; 친구초대\n");
      out.write("\t                      </a>\n");
      out.write("\t\t\t\t          <a href=\"#\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t\t                      <i class=\"fas fa-share-alt\"></i>&nbsp; 당근마켓 공유\n");
      out.write("\t                      </a>\n");
      out.write("\t\t\t\t          <a href=\"#\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t\t                      <i class=\"far fa-flag\"></i>&nbsp; 공지사항\n");
      out.write("\t                      </a>\n");
      out.write("\t\t\t\t          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/FAQ\" class=\"nav-link px-4 rounded-pill\">\n");
      out.write("\t\t                      <i class=\"far fa-question-circle\"></i>&nbsp; 자주 묻는 질문\n");
      out.write("\t                      </a>\n");
      out.write("\t\t\t\t        </nav>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div>\n");
      out.write("<!-- \t            <div class=\"py-4 px-4\">\n");
      out.write("\t                <div class=\"d-flex align-items-center justify-content-between mb-3\">\n");
      out.write("\t                    <h5 class=\"mb-0\">Recent photos</h5><a href=\"#\" class=\"btn btn-link text-muted\">Show all</a>\n");
      out.write("\t                </div>\n");
      out.write("\t                <div class=\"row\">\n");
      out.write("\t                    <div class=\"col-lg-6 mb-2 pr-lg-1\"><img src=\"https://images.unsplash.com/photo-1469594292607-7bd90f8d3ba4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80\" alt=\"\" class=\"img-fluid rounded shadow-sm\"></div>\n");
      out.write("\t                    <div class=\"col-lg-6 mb-2 pl-lg-1\"><img src=\"https://images.unsplash.com/photo-1493571716545-b559a19edd14?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80\" alt=\"\" class=\"img-fluid rounded shadow-sm\"></div>\n");
      out.write("\t                    <div class=\"col-lg-6 pr-lg-1 mb-2\"><img src=\"https://images.unsplash.com/photo-1453791052107-5c843da62d97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80\" alt=\"\" class=\"img-fluid rounded shadow-sm\"></div>\n");
      out.write("\t                    <div class=\"col-lg-6 pl-lg-1\"><img src=\"https://images.unsplash.com/photo-1475724017904-b712052c192a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80\" alt=\"\" class=\"img-fluid rounded shadow-sm\"></div>\n");
      out.write("\t                </div>\n");
      out.write("\t            </div> -->\n");
      out.write("\t        </div>\n");
      out.write("\t    </div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005frequestEncoding_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:requestEncoding
    org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag _jspx_th_fmt_005frequestEncoding_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag) _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag.class);
    boolean _jspx_th_fmt_005frequestEncoding_005f0_reused = false;
    try {
      _jspx_th_fmt_005frequestEncoding_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005frequestEncoding_005f0.setParent(null);
      // /WEB-INF/views/member/mypage.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005frequestEncoding_005f0.setValue("utf-8");
      int _jspx_eval_fmt_005frequestEncoding_005f0 = _jspx_th_fmt_005frequestEncoding_005f0.doStartTag();
      if (_jspx_th_fmt_005frequestEncoding_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005frequestEncoding_005f0);
      _jspx_th_fmt_005frequestEncoding_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005frequestEncoding_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005frequestEncoding_005f0_reused);
    }
    return false;
  }
}
